@startuml
skinparam classAttributeIconSize 0
class User{
- id : Long
- name : String
- passwordHash : String
- displayName : String
- email : String
- picture : String
- groups : Set<Group>
- dateCreated : OffsetDateTime
- lastUpdated : OffsetDateTime
}
class Group{
- id : Long
- name : String
- displayName : String
- email : String
- picture : String
- user : Set<User>
- dateCreated : OffsetDateTime
- lastUpdated : OffsetDateTime
}
@enduml